# Generated by Django 4.2 on 2024-02-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido',
            new_name='numPedido',
        ),
    ]
