# Generated by Django 4.2 on 2024-03-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_clientesform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientesform',
        ),
    ]
