# Generated by Django 4.2 on 2024-03-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_blog_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor',
        ),
    ]
